name: Create Virtual Desktop

on:
  workflow_dispatch:  # Enable manual triggering

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download and Install Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
        Move-Item ngrok.exe /usr/local/bin/ngrok  # Assuming ngrok is in your PATH

    - name: Start Virtual Desktop
      run: |
        # Insert commands here to start your virtual desktop environment
        # Example:
        # Start-Process "C:\path\to\your\virtualdesktop.exe"

    - name: Expose Virtual Desktop with Ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 3389  # Replace 3389 with the port your virtual desktop is running on
